[package]
name = "hash_cons"
authors = ["Karan Ahluwalia"]
version = "0.1.0"
edition = "2021"
descirption = "A type-safe hash consing library for rust"
readme = "readme.adoc"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["single-threaded"]
single-threaded = []
thread-safe = []

[dev-dependencies]
rand = "0.8.5"

[dependencies]