name: Rust

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Format
        run: cargo fmt --verbose

      - name: Build
        run: cargo build --all-features --verbose

      - name: For multi-threaded and auto-cleanup enabled tests (default)
        run: cargo test --verbose

      - name: For multi-threaded and auto-cleanup disabled tests
        run: cargo test --no-default-features --verbose

      - name: For single-threaded and auto-cleanup enabled tests
        run: cargo test --features "single-threaded" --verbose

      - name: For single-threaded and auto-cleanup disabled tests
        run: cargo test --no-default-features --features "single-threaded" --verbose